var game=document.createElement("div");
game.setAttribute("class","game");
document.body.append(game);
var grid=document.createElement("div");
grid.setAttribute("class","grid");
game.appendChild(grid);

var b1=document.createElement("button");
b1.innerHTML="1";
grid.appendChild(b1);
var b2=document.createElement("button");
b2.innerHTML="2";
grid.appendChild(b2);
var b3=document.createElement("button");
b3.innerHTML="3";
grid.appendChild(b3);
var b4=document.createElement("button");
b4.innerHTML="4";
grid.appendChild(b4);
var b5=document.createElement("button");
b5.innerHTML="5";
grid.appendChild(b5);
var b6=document.createElement("button");
b6.innerHTML="6";
grid.appendChild(b6);
var b7=document.createElement("button");
b7.innerHTML="7";
grid.appendChild(b7);
var b8=document.createElement("button");
b8.innerHTML="8";
grid.appendChild(b8);
var b9=document.createElement("button");
b9.innerHTML="9";
grid.appendChild(b9);
var b10=document.createElement("button");
b10.innerHTML="10";
grid.appendChild(b10);
var b11=document.createElement("button");
b11.innerHTML="11";
grid.appendChild(b11);
var b12=document.createElement("button");
b12.innerHTML="12";
grid.appendChild(b12);
var b13=document.createElement("button");
b13.innerHTML="13";
grid.appendChild(b13);
var b14=document.createElement("button");
b14.innerHTML="14";
grid.appendChild(b14);
var b15=document.createElement("button");
b15.innerHTML="15";
grid.appendChild(b15);
var b16=document.createElement("button");
b16.innerHTML=" ";
grid.appendChild(b16);

var footer=document.createElement('div');
footer.setAttribute("class","footer");
game.appendChild(footer);
var play=document.createElement("button");
play.innerHTML="play";
footer.appendChild(play);
var move=document.createElement("span");
move.setAttribute('id','move')
move.innerHTML="Move : 0";
footer.appendChild(move);
var time=document.createElement("span");
time.setAttribute("id","time");
time.innerHTML="Time : 0";
footer.appendChild(time);
var msg=document.createElement("h1");
msg.setAttribute("class","message");
msg.innerHTML="You Win";
document.body.append(msg);